version: '3.4'

services:

  redis:
    container_name: redisCache
    image: redis:6-alpine
    expose:
      - "6379"
    ports:
      - "6379:6379"
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redisCommander
    environment:
      - REDIS_HOSTS=redis
    ports:
      - "8013:8081"
    depends_on:
      - redis

  catalog.microservice:
    container_name: catalogmicroservice
    environment:
      - ASPNETCORE_ENVIRONMENT=Development      
    ports:
      - "8001:80"     
    depends_on:
      - elasticsearch      
      - kibana
      - redis
    volumes:
      - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
      - ${HOME}/.aspnet/https:/root/.aspnet/https/

  customer.microservice:
    container_name: customermicroservice
    environment:
        - ASPNETCORE_ENVIRONMENT=Development      
    ports:
        - "8002:80"      
    volumes:
        - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
        - ${HOME}/.aspnet/https:/root/.aspnet/https/

  delivery.microservice:
    container_name: deliverymicroservice
    environment:
        - ASPNETCORE_ENVIRONMENT=Development      
    ports:
        - "8003:80"      
    volumes:
        - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
        - ${HOME}/.aspnet/https:/root/.aspnet/https/

  order.microservice:
    container_name: ordermicroservice
    environment:
        - ASPNETCORE_ENVIRONMENT=Development      
    ports:
        - "8004:80"      
    volumes:
        - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
        - ${HOME}/.aspnet/https:/root/.aspnet/https/

  gateway.api:
    container_name: gatewayapi
    environment:
        - ASPNETCORE_ENVIRONMENT=Development     
    depends_on :
        - catalog.microservice
        - customer.microservice
        - delivery.microservice
        - order.microservice
        - elasticsearch
        - kibana
    ports:
        - "7001:80"    
    volumes:
        - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
        - ${HOME}/.aspnet/https:/root/.aspnet/https/
